hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dunst")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("waybar")
    hl.exec_cmd("discord")
    hl.exec_cmd("steam -silent")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("juhradial-mx")
    hl.exec_cmd("kando")
end)
